print("Starting program....")
print("Executing sequence....")
print("**********************")
print("*********************")
print("********************")
print("*******************")
print("******************")
print("*****************")
print("****************")
print("***************")
print("**************")
print("*************")
print("************")
print("***********")
print("**********")
print("*********")
print("********")
print("*******")
print("******")
print("*****")
print("****")
print("***")
print("**")
print("*")
print("Sequence Execution Completed!")